<program> ::= <expression>

<expression> ::= <atom> | <list>

<atom> ::= <symbol> | <number> | <boolean> | <string>

<symbol> ::= <letter>

<number> ::= <integer>

<integer> ::= <digit>

<boolean> ::= "true" | "false"

<string> ::= "\"" <character> "\""

<list> ::= "(" <expression> ")"

<character> ::= <letter>

<letter> ::= "a" | "b" | ... | "z" | "A" | "B" | ... | "Z"

<digit> ::= "0" | "1" | ... | "9"

<special-char> ::= "+" | "-" | "*" | "/" | "%" | "<" | "?"