name: attempt 14

on:
  push:
    branches:
      - main

jobs:
  clone-epitech:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Clone Epitech repository
      run: |
        git clone git@github.com:EpitechPromo2026/B-FUN-500-PAR-5-2-glados-hugo.mouraud.git epitech-repo
        cd epitech-repo
        ls -la 
