name: attempt 13

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Do nothing
      run: echo "This GitHub Action does nothing."

    - name: Print a message
      run: echo "GitHub Action ran successfully!"
